# Generated by Django 5.1.3 on 2024-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aqscore_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.CharField(max_length=50)),
                ('A2', models.CharField(max_length=50)),
                ('A3', models.CharField(max_length=50)),
                ('A4', models.CharField(max_length=50)),
                ('A5', models.CharField(max_length=50)),
                ('A6', models.CharField(max_length=50)),
                ('A7', models.CharField(max_length=50)),
                ('A8', models.CharField(max_length=50)),
                ('A9', models.CharField(max_length=50)),
                ('A10', models.CharField(max_length=50)),
                ('totalscore', models.IntegerField()),
            ],
        ),
    ]
