# Generated by Django 5.1.3 on 2024-12-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aqscore_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aqscore_table',
        ),
    ]
