# Generated by Django 5.1.3 on 2024-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_aqscore_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQscore_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.IntegerField()),
                ('A2', models.IntegerField()),
                ('A3', models.IntegerField()),
                ('A4', models.IntegerField()),
                ('A5', models.IntegerField()),
                ('A6', models.IntegerField()),
                ('A7', models.IntegerField()),
                ('A8', models.IntegerField()),
                ('A9', models.IntegerField()),
                ('A10', models.IntegerField()),
                ('totalscore', models.IntegerField()),
            ],
        ),
    ]
