# Generated by Django 5.1.3 on 2024-12-14 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_aqscore_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignstudy_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('SM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studymaterials_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
    ]
