# Generated by Django 3.2.25 on 2025-01-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_assignstudy_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_type_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('file', models.CharField(max_length=100)),
            ],
        ),
    ]
