# Generated by Django 3.2.25 on 2025-01-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_video_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_frame',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sm_type_table'),
        ),
    ]
